### ISSUE TITLE
@Deta

### ISSUE THREAD

**Issue by predetermined** [l2ig/deta-deno#1]
I'd be happy to hand this project over to you whenever you'd like.

For the moment, I'll be adding more services as I need them or when I'm just bored. But I'll try to keep this module up-to-date.

Oh, and... Deta is cool! :)

(cc @abdelhai)

**Comment by abdelhai** [comment]
Hey Leonard! This looks really cool, we were planning on publishing our own Deno SDK.
Let me discuss with the team and get back to you with the next steps :)
Could we reach out via email instead of GH?
@l2ig

**Comment by predetermined** [comment]
@abdelhai Yes, sure and very nice to hear! (leonard@linters.de)
